server:
  port: 18083
dubbo:
  application:
    name: tanhua-manage
  registry:
    address: zookeeper://192.168.211.160:2181
  consumer:
    check: false
# log
logging:
  level:
    root: info
    com:
      tanhua: debug
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %msg - %logger{15}%n\'
# 第三配置
tanhua:
  # jwt的密钥itcast_tanhua md5
  secret: 76bd425b6f29f7fcc2e0bfc286043df1
  # redis key prefix for validate code
  redisValidateCodeKeyPrefix: VALIDATECODE_
  # 阿里大宇短信配置
  sms:
    signName: 黑马程序员
    parameterName: code
    validateCodeTemplateCode: SMS_164508533
    accessKeyId: LTAI5tDRHQk6hfL9JWTcDpWo
    accessKeySecret: UP9EpSxxSYWcMLNpdBSYMW1keEkdL3
  # oss存储
  oss:
    endpoint: http://oss-cn-shenzhen.aliyuncs.com
    bucketName: sz-114
    url: https://sz-114.oss-cn-shenzhen.aliyuncs.com
    accessKeyId: LTAI5tDRHQk6hfL9JWTcDpWo
    accessKeySecret: UP9EpSxxSYWcMLNpdBSYMW1keEkdL3
  # 百度人脸检测
  face:
    appId: 22949516
    apiKey: uDkEBDhtO02soeMB6kuMZTZi
    secretKey: sMGUX8tzPhc0eBfvy3rbGYuXiK6MZCEF
  huanxin:
    url: http://a1.easemob.com/
    orgName: 1100210128203775
    appName: tanhua
    clientId: YXA69S_vv-QlQmaJcXFr8VgFuA
    clientSecret: YXA6geW8sILBJtyVk2JEPmgrWG1P99k
  huawei:
    username: HW_NO9527
    password: bB123456
    project: cn-east-3
    domain: HW_NO9527
    # 图片检测内容 politics：是否涉及政治人物的检测，terrorism：是否包含涉政暴恐元素的检测，porn：是否包含涉黄内容元素的检测，ad：是否包含广告的检测（公测特性），all：包含politics、terrorism和porn三种场景的检测
    categoriesImage: politics,terrorism,porn
    # 文字检测内容 politics：涉政，porn：涉黄，ad：广告，abuse：辱骂，contraband：违禁品，flood：灌水
    categoriesText: politics,porn,ad,abuse,contraband,flood
    # 文本审核内容的地址
    textApiUrl: https://moderation.cn-east-3.myhuaweicloud.com/v1.0/moderation/text
    # 图像审核地址
    imageApiUrl: https://moderation.cn-east-3.myhuaweicloud.com/v1.0/moderation/image/batch
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sz114_tanhua_manager?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: root
  redis:
    host: 192.168.211.160
    port: 6379
  servlet:
    multipart:
      max-file-size: 10MB
# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1500
  connect-timeout: 600
  #缩略图生成参数
  thumb-image:
    width: 150
    height: 150
  #TrackerList参数,支持多个
  tracker-list: 192.168.211.160:22122
  web-server-url: http://192.168.211.160:8888/
#mybaits-plus
mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb_    #数据库表前缀
      id-type: auto        #数据库表主键的策略

rocketmq:
  name-server: 192.168.211.160:9876
